In [3]:
import pandas as pd
import numpy as np
import math

### with sklearn

In [74]:
# this is CountV with sklearn 
from sklearn.feature_extraction.text import CountVectorizer

# Data contoh
data = [
    "Saya suka makan nasi goreng.",
    "Nasi goreng enak dan lezat.",
    "Makanan favorit saya adalah nasi goreng.",
    " "
]

# Inisialisasi CountVectorizer
vectorizer = CountVectorizer()

# Melakukan tokenisasi dan pembuatan vektor
vectors = vectorizer.fit_transform(data)

# Hasil vektor dalam bentuk matriks
print("Matriks Vektor:")
print(vectors.toarray())

# Vocabulary (daftar kata unik)
print("Vocabulary:")
print(vectorizer.get_feature_names_out())

Matriks Vektor:
[[0 0 0 0 1 0 1 0 1 1 1]
 [0 1 1 0 1 1 0 0 1 0 0]
 [1 0 0 1 1 0 0 1 1 1 0]
 [0 0 0 0 0 0 0 0 0 0 0]]
Vocabulary:
['adalah' 'dan' 'enak' 'favorit' 'goreng' 'lezat' 'makan' 'makanan' 'nasi'
 'saya' 'suka']


### secara manual

In [6]:
# memasukan setiap kata unik dalam set
words_set = set()

for doc in  data:
    doc = doc.lower()
    words = doc.split(' ')
    words_set = words_set.union(set(words))

# sama cuman bedanya ini nanti digunakan untuk memberi nama kolom sehingga harus dalam array (convert to array)
colom = []
for i in words_set:
    colom.append(i)


     
print('Number of unique words in the corpus:',len(words_set))
print('The words in the corpus: \n', np.array(words_set))

Number of unique words in the corpus: 12
The words in the corpus: 
 {'goreng', 'saya', 'makan', 'makanan', 'dan', 'enak', 'nasi', 'favorit', 'suka', 'adalah', 'goreng.', 'lezat.'}


In [7]:
n_docs = len(data)         #·Number of documents in the corpus
n_words_set = len(words_set) #·Number of unique words in the
data_dum = np.zeros((n_docs, n_words_set))

print(data_dum)
print(words_set)

countV = pd.DataFrame(np.zeros((n_docs, n_words_set)), columns=colom)

# Compute Term Frequency (TF)
for i in range(n_docs):
    words = data[i].lower().split(' ') # Words in the document
    for w in words:
        # menghitung dengan (jumlah kata(t) muncul dalam sebuah dokumen)
        countV[w][i] = countV[w][i] + (data[i].lower().count(w))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
{'goreng', 'saya', 'makan', 'makanan', 'dan', 'enak', 'nasi', 'favorit', 'suka', 'adalah', 'goreng.', 'lezat.'}


In [8]:
countV

goreng  saya  makan  makanan  dan  enak  nasi  favorit  suka  adalah  \
0     0.0   1.0    1.0      0.0  0.0   0.0   1.0      0.0   1.0     0.0   
1     1.0   0.0    0.0      0.0  1.0   1.0   1.0      0.0   0.0     0.0   
2     0.0   1.0    0.0      1.0  0.0   0.0   1.0      1.0   0.0     1.0   

   goreng.  lezat.  
0      1.0     0.0  
1      0.0     1.0  
2      1.0     0.0

In [9]:
data

['Saya suka makan nasi goreng.',
 'Nasi goreng enak dan lezat.',
 'Makanan favorit saya adalah nasi goreng.']

In [69]:
new = pd.DataFrame(data=data, columns=['kalimat'])
new = new.astype('string')
new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 1 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   kalimat  3 non-null      string
dtypes: string(1)
memory usage: 156.0 bytes


In [70]:
kata = 'suka'


def cek_dan_hapus_baris(row):
    if kata in row.lower():
        print('Ditemukan dalam', row)
        return pd.NA
    else:
        return row
    
new['kalimat'] = new['kalimat'].apply(cek_dan_hapus_baris)
new = new.dropna()

Ditemukan dalam Saya suka makan nasi goreng.


In [76]:
for i in data:
    print(i ,"memiliki panjang", len(i))

Saya suka makan nasi goreng. memiliki panjang 28
Nasi goreng enak dan lezat. memiliki panjang 27
Makanan favorit saya adalah nasi goreng. memiliki panjang 40
  memiliki panjang 1
