In [2]:
import pandas as pd
import numpy as np
import math

In [11]:
corpus = ['data science is one of the most important fields of science',
          'this is one of the best data science courses',
          'data scientists analyze data']

corp = pd.DataFrame(corpus, columns=['teks'])

### with sklearn

In [57]:
# this is CountV with sklearn 
from sklearn.feature_extraction.text import CountVectorizer

# Inisialisasi CountVectorizer
vectorizer = CountVectorizer()

# Melakukan tokenisasi dan pembuatan vektor
vectors = vectorizer.fit_transform(corpus)

# Hasil vektor dalam bentuk matriks
print("Matriks Vektor:")
print(vectors.toarray())

# Vocabulary (daftar kata unik)
print("Vocabulary:")
print(vectorizer.get_feature_names_out())

Matriks Vektor:
[[0 0 0 1 1 1 1 1 2 1 2 0 1 0]
 [0 1 1 1 0 0 1 0 1 1 1 0 1 1]
 [1 0 0 2 0 0 0 0 0 0 0 1 0 0]]
Vocabulary:
['analyze' 'best' 'courses' 'data' 'fields' 'important' 'is' 'most' 'of'
 'one' 'science' 'scientists' 'the' 'this']


In [58]:
sklearn_count = pd.DataFrame(vectors.toarray(), columns=vectorizer.get_feature_names_out())

In [59]:
sklearn_count

analyze  best  courses  data  fields  important  is  most  of  one  \
0        0     0        0     1       1          1   1     1   2    1   
1        0     1        1     1       0          0   1     0   1    1   
2        1     0        0     2       0          0   0     0   0    0   

   science  scientists  the  this  
0        2           0    1     0  
1        1           0    1     1  
2        0           1    0     0

### secara manual

In [55]:
def uniq_word(corpus):
    words_set = set()
    for doc in  corpus:
        doc = doc.lower()
        words = doc.split(' ')
        words_set = words_set.union(set(words))
    return words_set

def countV(corpus):
    corpus = np.array(corpus)
    corpus = corpus.astype(str)
    
    words_set = uniq_word(corpus)

    # make word_set as array (for making a table)
    colom = []
    for i in words_set:
        colom.append(i)

    n_docs = len(corpus)         #·Number of documents in the corpus
    n_words_set = len(words_set) #·Number of unique words in the

    countV = pd.DataFrame(np.zeros((n_docs, n_words_set)), columns=colom)

    # Compute Term Frequency (TF)
    for i in range(n_docs):
        for w in words_set:
        # menghitung dengan (jumlah kata(t) muncul dalam sebuah dokumen)
            countV[w][i] = countV[w][i] + (corpus[i].lower().count(w))
    
    return countV

In [56]:
manual = countV(corpus)
manual

is  the  analyze   of  one  courses  fields  scientists  most  important  \
0  1.0  1.0      0.0  2.0  1.0      0.0     1.0         0.0   1.0        1.0   
1  2.0  1.0      0.0  1.0  1.0      1.0     0.0         0.0   0.0        0.0   
2  1.0  0.0      1.0  0.0  0.0      0.0     0.0         1.0   0.0        0.0   

   data  this  science  best  
0   1.0   0.0      2.0   0.0  
1   1.0   1.0      1.0   1.0  
2   2.0   0.0      0.0   0.0

In [24]:
hasil = corpus[0].lower().count('of')
print(hasil)

2


In [26]:
# memasukan setiap kata unik dalam set
words_set = set()

for doc in  corpus:
    doc = doc.lower()
    words = doc.split(' ')
    words_set = words_set.union(set(words))

# sama cuman bedanya ini nanti digunakan untuk memberi nama kolom sehingga harus dalam array (convert to array)
colom = []
for i in words_set:
    colom.append(i)


     
print('Number of unique words in the corpus:',len(words_set))
print('The words in the corpus: \n', np.array(words_set))

Number of unique words in the corpus: 14
The words in the corpus: 
 {'is', 'the', 'analyze', 'of', 'one', 'courses', 'fields', 'scientists', 'most', 'important', 'data', 'this', 'science', 'best'}


In [46]:
n_docs = len(corpus)         #·Number of documents in the corpus
n_words_set = len(words_set) #·Number of unique words in the
data_dum = np.zeros((n_docs, n_words_set))

print(data_dum)
print(words_set)

countV = pd.DataFrame(np.zeros((n_docs, n_words_set)), columns=colom)



[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
{'is', 'the', 'analyze', 'of', 'one', 'courses', 'fields', 'scientists', 'most', 'important', 'data', 'this', 'science', 'best'}


In [47]:
countV

is  the  analyze   of  one  courses  fields  scientists  most  important  \
0  0.0  0.0      0.0  0.0  0.0      0.0     0.0         0.0   0.0        0.0   
1  0.0  0.0      0.0  0.0  0.0      0.0     0.0         0.0   0.0        0.0   
2  0.0  0.0      0.0  0.0  0.0      0.0     0.0         0.0   0.0        0.0   

   data  this  science  best  
0   0.0   0.0      0.0   0.0  
1   0.0   0.0      0.0   0.0  
2   0.0   0.0      0.0   0.0

In [48]:
# Compute Term Frequency (TF)
for i in range(n_docs):
    words = corpus[i].lower().split(' ') # Words in the document
    print('cek kalimat ',corpus[i])
    for w in words:
        print('kata:', w)
        # menghitung dengan (jumlah kata(t) muncul dalam sebuah dokumen)
        print('jumlah',countV[w][i])
        countV[w][i] = countV[w][i] + (corpus[i].lower().count(w))


cek kalimat  data science is one of the most important fields of science
kata: data
jumlah 0.0
kata: science
jumlah 0.0
kata: is
jumlah 0.0
kata: one
jumlah 0.0
kata: of
jumlah 0.0
kata: the
jumlah 0.0
kata: most
jumlah 0.0
kata: important
jumlah 0.0
kata: fields
jumlah 0.0
kata: of
jumlah 2.0
kata: science
jumlah 2.0


KeyboardInterrupt: 

In [39]:
countV

is  the  analyze   of  one  courses  fields  scientists  most  important  \
0  2.0  2.0      0.0  8.0  2.0      0.0     2.0         0.0   2.0        2.0   
1  4.0  2.0      0.0  2.0  2.0      2.0     0.0         0.0   0.0        0.0   
2  0.0  0.0      2.0  0.0  0.0      0.0     0.0         2.0   0.0        0.0   

   data  this  science  best  
0   2.0   0.0      8.0   0.0  
1   2.0   2.0      2.0   2.0  
2   8.0   0.0      0.0   0.0

In [9]:
data

['Saya suka makan nasi goreng.',
 'Nasi goreng enak dan lezat.',
 'Makanan favorit saya adalah nasi goreng.']

In [69]:
new = pd.DataFrame(data=data, columns=['kalimat'])
new = new.astype('string')
new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 1 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   kalimat  3 non-null      string
dtypes: string(1)
memory usage: 156.0 bytes


In [70]:
kata = 'suka'


def cek_dan_hapus_baris(row):
    if kata in row.lower():
        print('Ditemukan dalam', row)
        return pd.NA
    else:
        return row
    
new['kalimat'] = new['kalimat'].apply(cek_dan_hapus_baris)
new = new.dropna()

Ditemukan dalam Saya suka makan nasi goreng.


In [76]:
for i in data:
    print(i ,"memiliki panjang", len(i))

Saya suka makan nasi goreng. memiliki panjang 28
Nasi goreng enak dan lezat. memiliki panjang 27
Makanan favorit saya adalah nasi goreng. memiliki panjang 40
  memiliki panjang 1
