### cara 1

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

# Sample corpus
corpus = ["I love this movie",
          "This movie is terrible",
          "The plot is confusing"]

vectorizer = CountVectorizer()
bow_encoded = vectorizer.fit_transform(corpus)

In [ ]:
import pandas as pd
import numpy as np
from math import log
from nltk.tokenize import word_tokenize
def word_tokenize_wrapper(text):
    return word_tokenize(text)

def create_wordBank(documents):
    result = pd.DataFrame()
    document_tokens = [doc.split() for doc in documents]
    unique_words = [word for document in document_tokens for word in document]
    result['word'] = unique_words
    result = result['word'].drop_duplicates()
    return result

def idf(doc, wordBank):
 #hitung jumlah doc
 N = doc.count()
 #buat dataframe dengan header word dan idf
 result = pd.DataFrame(columns=['word', 'idf'])
 #untuk setiap kata pada wordBank lakukan.....
 for word in wordBank:
  #hitung jumlah doc yang mengandung kata word['words']
  dft = np.sum(doc.str.contains(word))
  #hitung inverse document frequency smooth
  idft = log(N / (dft + 1), 10)
  #tambahkan idf untuk setiap kata pada data frame
  result = pd.concat([result, pd.DataFrame({'word':[word],'idf':[idft]})], ignore_index=True)
 #return variable result
 return result

def tf(doc, wordBank):
  #split kata berdasarkan spasi
  wordList = doc.str.split(' ')
  #hitung jumlah kata pada setiap doc
  # maxFt = [len(s) for s in wordList]
  #buat DataFrame kosong untuk menyimpan hasil perhitungan Tf
  result = pd.DataFrame()
  #untuk setiap word dalam wordbank lakukan ....
  for word in wordBank:
    #hitung frekuensi kata untuk setiap doc
    ft = np.add([s.count(word) for s in wordList], 0)
    #tf log normalization
    ftd = 1 + np.log10(ft)
    #tambahkan hasil perhitungan tf kedalam DataFrame
    result = pd.concat([result, pd.Series(ftd)],ignore_index=True)
  #replace -inf with zero
  result = result.replace(-np.inf, 0)
  #return variable result
  return result

def tfIdf(tf, idf):
 #buat DataFrame kosong untuk menyimpan hasil perhitungan Tf-Idf
 result = pd.DataFrame()
 #untuk setiap tf
 for i in tf:
  #tf idf untuk document term weighting tf * idf
  tfIdf = tf[i] * idf['idf']
  #tambahkan hasil perhitungan tf idf kedalam DataFrame
  result = pd.concat([result, pd.Series(tfIdf)], ignore_index=True)
 #return variable result
 return result

In [ ]:
df = pd.Series({'word': ['aku'],'idf': [2]})
df

word    [aku]
idf       [2]
dtype: object

In [ ]:
corpus = ["I love this movie",
          "This movie is terrible",
          "The plot is confusing"]
corpus = pd.DataFrame(corpus)

# print(corpus.apply(word_tokenize_wrapper))
# resultIDF = idf(corpus, create_wordBank(corpus))
# #hitung nilai TF

len = corpus.index

jumlah = len+1

In [ ]:
data1 = pd.read_excel('dataset\SentimentIbu_kota_pindah_new.xlsx')
data1 = data1['text']
data1 = data1[:10]

In [ ]:
def clean_tweet(teks):
    return ''.join(re.sub("(@[A-Za-z0-9]+)|([^0-9A-Za-z \t])|(\w+\/\/\S+)","",teks))
def remove_number(text):
    return  re.sub(r"\d+", "", text)

#use function
clean = []
for i in data1:
    clean.append(clean_tweet(i))

data1 = pd.DataFrame(clean, columns=['teks'])

In [ ]:
data1 = data1['teks'].str.lower()
data1

0     maksudnya secara gak langsung mau bikin pembe...
1    ozil saya turut mendukung proses pemindahan ib...
2    kolaborasi menjadi salah satu kunci bagi pemer...
3    sch guys aku keterima di ilkom unpad  trivia s...
4     ayo kawal proses pemindahan ibukota ibukotane...
5     ayo kawal proses pemindahan ibukota ibukotane...
6    pemindahan ibukota negara dapat dimaknai lebih...
7     trump menangguhkan pemindahan ibukota israel ...
8    pemindahan ibu kota mataram kuno oleh mpu sind...
9     um pemindahan ibukota kan tidak memindahkan m...
Name: teks, dtype: object

In [ ]:
wordBank = create_wordBank(data1)
wordBank

0      maksudnya
1         secara
2            gak
3       langsung
4            mau
         ...    
188      problem
189          its
190      running
191         away
192         from
Name: word, Length: 145, dtype: object

In [ ]:
resultIDF = idf(data1, wordBank)

resultIDF

C:\Users\alam\AppData\Local\Temp\ipykernel_888\1558316671.py:28: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result = pd.concat([result, pd.DataFrame({'word':[word],'idf':[idft]})], ignore_index=True)


word      idf
0    maksudnya  0.69897
1       secara  0.69897
2          gak  0.69897
3     langsung  0.69897
4          mau  0.69897
..         ...      ...
140    problem  0.69897
141        its  0.69897
142    running  0.69897
143       away  0.69897
144       from  0.69897

[145 rows x 2 columns]

In [ ]:
resultTF = tf(data1, wordBank)
resultTF

C:\Users\alam\AppData\Local\Temp\ipykernel_888\1974542271.py:44: RuntimeWarning: divide by zero encountered in log10
  ftd = 1 + np.log10(ft)


0
0     1.0
1     0.0
2     0.0
3     0.0
4     0.0
...   ...
1445  0.0
1446  0.0
1447  0.0
1448  0.0
1449  1.0

[1450 rows x 1 columns]

### cara2

In [1]:
import pandas as pd
import numpy as np
    import math

In [2]:
corpus = ['data science is one of the most important fields of science',
          'this is one of the best data science courses',
          'data scientists analyze data']

corp = pd.DataFrame(corpus, columns=['teks'])

In [3]:
teks = np.array(corp['teks'])
teks = teks.astype(str)
teks

array(['data science is one of the most important fields of science',
       'this is one of the best data science courses',
       'data scientists analyze data'], dtype='<U59')

In [6]:
# menghitung kata unik yang ada di dalam corpus
def uniq_word(corpus):
    words_set = set()
    for doc in  corpus:
        doc = doc.lower()
        words = doc.split(' ')
        words_set = words_set.union(set(words))
    return words_set

def compute_tf(words_set, corpus,colom):
    n_docs = len(corpus)         #·Number of documents in the corpus
    n_words_set = len(words_set) #·Number of unique words in the
    df_tf = pd.DataFrame(np.zeros((n_docs, n_words_set)), columns=colom)

    # Compute Term Frequency (TF)
    for i in range(n_docs):
        words = corpus[i].split(' ') # memcah semua kata(tokenisasi) yang ada dalam document
        # each loop untuk menghitung bobot tf semua kata yang ada dalam doc 
        for w in words_set:
            # menghitung dengan (jumlah kata(t) muncul dalam sebuah dokumen / jumlah seluruh kata yang ada dalam dokumen)
            df_tf[w][i] = df_tf[w][i] + (corpus[i].count(w) / len(words))
    return df_tf

def compute_idf(words_set,n_docs,corpus):
    idf = {}
    print('the idf :')
    for w in words_set:
        k = 0    # number of documents in the corpus that contain this word
     
        # looping untuk menghitung jumlah dokumen yang mengandung kata(T)
        for i in range(n_docs):
            if w in corpus[i].split():
                k += 1

        # menghitung idf dengan cara log(jumlah sentimen(doc) dalam corpus/jumlah sentiment(doc) yang menggandung kata unik itu)
        # # kalau menggunakan sklearn formulanya agak sedikti berbeda dimana dia menggunakan log(1+ jumlah sentimen(doc) dalam corpus/ 1+jumlah sentiment(doc) yang menggandung kata unik itu)+1  
        idf[w] =  math.log(n_docs / k)
        print(f'{w:>15}: {idf[w]:>10}' )
    return idf

def tf_idf_manual(corpus):
    corpus = np.array(corpus)
    corpus = corpus.astype(str)
    
    # jumlah semua kata unik yang ada dalam corpus
    words_set = uniq_word(corpus)

    # make word_set as array (for making a table)
    colom = []
    for i in words_set:
        colom.append(i)

    n_docs = len(corpus)         #·Number of documents in the corpus
    n_words_set = len(words_set) #·Number of unique words in the

    df_tf = compute_tf(words_set,corpus,colom)
    print('the df_tf',df_tf)
    df_tf_idf = df_tf.copy()

    idf = compute_idf(words_set,n_docs,corpus)

    for w in words_set:
        for i in range(n_docs):
            df_tf_idf[w][i] = df_tf[w][i] * idf[w]
         
    return df_tf_idf


In [7]:
manual = tf_idf_manual(corp['teks'])
manual

the df_tf        most  important   courses        is    fields        of   science  \
0  0.090909   0.090909  0.000000  0.090909  0.090909  0.181818  0.181818   
1  0.000000   0.000000  0.111111  0.222222  0.000000  0.111111  0.111111   
2  0.000000   0.000000  0.000000  0.250000  0.000000  0.000000  0.000000   

       this       the      best      data  scientists  analyze       one  
0  0.000000  0.090909  0.000000  0.090909        0.00     0.00  0.090909  
1  0.111111  0.111111  0.111111  0.111111        0.00     0.00  0.111111  
2  0.000000  0.000000  0.000000  0.500000        0.25     0.25  0.000000  
the idf :
           most: 1.0986122886681098
      important: 1.0986122886681098
        courses: 1.0986122886681098
             is: 0.4054651081081644
         fields: 1.0986122886681098
             of: 0.4054651081081644
        science: 0.4054651081081644
           this: 1.0986122886681098
            the: 0.4054651081081644
           best: 1.0986122886681098
           data

most  important   courses        is    fields        of   science  \
0  0.099874   0.099874  0.000000  0.036860  0.099874  0.073721  0.073721   
1  0.000000   0.000000  0.122068  0.090103  0.000000  0.045052  0.045052   
2  0.000000   0.000000  0.000000  0.101366  0.000000  0.000000  0.000000   

       this       the      best  data  scientists   analyze       one  
0  0.000000  0.036860  0.000000   0.0    0.000000  0.000000  0.036860  
1  0.122068  0.045052  0.122068   0.0    0.000000  0.000000  0.045052  
2  0.000000  0.000000  0.000000   0.0    0.274653  0.274653  0.000000

In [64]:
x = np.array(manual)
x.shape

(3, 14)

In [38]:
words_set = set()
 
for doc in  teks:
    words = doc.split(' ')
    words_set = words_set.union(set(words))


     
print('Number of unique words in the corpus:',len(words_set))
print('The words in the corpus: \n', np.array(words_set))

Number of unique words in the corpus: 14
The words in the corpus: 
 {'data', 'science', 'is', 'the', 'scientists', 'best', 'courses', 'important', 'this', 'one', 'analyze', 'of', 'most', 'fields'}


In [39]:
colom = []
for i in words_set:
    colom.append(i)

In [50]:
n_docs = len(teks)         #·Number of documents in the corpus
n_words_set = len(words_set) #·Number of unique words in the
data_dum = np.zeros((n_docs, n_words_set))

print(data_dum)
print(words_set)

df_tf = pd.DataFrame(np.zeros((n_docs, n_words_set)), columns=colom)

# Compute Term Frequency (TF)
for i in range(n_docs):
    words = teks[i].split(' ') # Words in the document
    for w in words:
        # menghitung dengan (jumlah kata(t) muncul dalam sebuah dokumen / jumlah seluruh kata yang ada dalam dokumen)
        df_tf[w][i] = df_tf[w][i] + (teks[i].count(w) / len(words))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
{'data', 'science', 'is', 'the', 'scientists', 'best', 'courses', 'important', 'this', 'one', 'analyze', 'of', 'most', 'fields'}


In [55]:
df_tf

data   science        is       the  scientists      best   courses  \
0  0.090909  0.363636  0.090909  0.090909        0.00  0.000000  0.000000   
1  0.111111  0.111111  0.222222  0.111111        0.00  0.111111  0.111111   
2  1.000000  0.000000  0.000000  0.000000        0.25  0.000000  0.000000   

   important      this       one  analyze        of      most    fields  
0   0.090909  0.000000  0.090909     0.00  0.363636  0.090909  0.090909  
1   0.000000  0.111111  0.111111     0.00  0.111111  0.000000  0.000000  
2   0.000000  0.000000  0.000000     0.25  0.000000  0.000000  0.000000

In [57]:
print("IDF of: ")
 
idf = {}
 
for w in words_set:
    k = 0    # number of documents in the corpus that contain this word
     
    # looping untuk menghitung jumlah dokumen yang mengandung kata(T)
    for i in range(n_docs):
        if w in teks[i].split():
            k += 1

    # menghitung idf dengan cara log(jumlah sentimen(doc) dalam corpus/jumlah sentiment(doc) yang menggandung kata unik itu)
    # # kalau menggunakan sklearn formulanya agak sedikti berbeda dimana dia menggunakan log(1+ jumlah sentimen(doc) dalam corpus/ 1+jumlah sentiment(doc) yang menggandung kata unik itu)+1  
    idf[w] =  math.log(n_docs / k)
     
    print(f'{w:>15}: {idf[w]:>10}' )

IDF of: 
           data:        0.0
        science: 0.4054651081081644
             is: 0.4054651081081644
            the: 0.4054651081081644
     scientists: 1.0986122886681098
           best: 1.0986122886681098
        courses: 1.0986122886681098
      important: 1.0986122886681098
           this: 1.0986122886681098
            one: 0.4054651081081644
        analyze: 1.0986122886681098
             of: 0.4054651081081644
           most: 1.0986122886681098
         fields: 1.0986122886681098


In [58]:
df_tf_idf = df_tf.copy()
 
for w in words_set:
    for i in range(n_docs):
        df_tf_idf[w][i] = df_tf[w][i] * idf[w]
         
df_tf_idf

data   science        is       the  scientists      best   courses  \
0   0.0  0.147442  0.036860  0.036860    0.000000  0.000000  0.000000   
1   0.0  0.045052  0.090103  0.045052    0.000000  0.122068  0.122068   
2   0.0  0.000000  0.000000  0.000000    0.274653  0.000000  0.000000   

   important      this       one   analyze        of      most    fields  
0   0.099874  0.000000  0.036860  0.000000  0.147442  0.099874  0.099874  
1   0.000000  0.122068  0.045052  0.000000  0.045052  0.000000  0.000000  
2   0.000000  0.000000  0.000000  0.274653  0.000000  0.000000  0.000000

In [14]:
array_tf_idf = np.array(df_tf_idf)
array_tf_idf.shape

(3, 14)

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer

tr_idf_model  = TfidfVectorizer()
tf_idf_vector = tr_idf_model.fit_transform(corpus)

tf_idf_array = tf_idf_vector.toarray()
 
tf_idf_array

array([[0.        , 0.        , 0.        , 0.18952581, 0.32089509,
        0.32089509, 0.24404899, 0.32089509, 0.48809797, 0.24404899,
        0.48809797, 0.        , 0.24404899, 0.        ],
       [0.        , 0.40029393, 0.40029393, 0.23642005, 0.        ,
        0.        , 0.30443385, 0.        , 0.30443385, 0.30443385,
        0.30443385, 0.        , 0.30443385, 0.40029393],
       [0.54270061, 0.        , 0.        , 0.64105545, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.54270061, 0.        , 0.        ]])

In [13]:
tf_idf_array.shape

(3, 14)

In [73]:
words_set = tr_idf_model.get_feature_names_out()

tes = pd.DataFrame(tf_idf_array, columns=words_set)

tes

analyze      best   courses      data    fields  important        is  \
0  0.000000  0.000000  0.000000  0.189526  0.320895   0.320895  0.244049   
1  0.000000  0.400294  0.400294  0.236420  0.000000   0.000000  0.304434   
2  0.542701  0.000000  0.000000  0.641055  0.000000   0.000000  0.000000   

       most        of       one   science  scientists       the      this  
0  0.320895  0.488098  0.244049  0.488098    0.000000  0.244049  0.000000  
1  0.000000  0.304434  0.304434  0.304434    0.000000  0.304434  0.400294  
2  0.000000  0.000000  0.000000  0.000000    0.542701  0.000000  0.000000

In [1]:
import numpy as np

# Contoh array
arr = np.array([0, 1, 1, 3, 2, 1, 7])

# Menggunakan np.bincount() untuk menghitung frekuensi
bincount_result = np.bincount(arr)

print(bincount_result)

[1 3 1 1 0 0 0 1]
